name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementart/docker:unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y folks glib-2.0 gobject-2.0 granite gtk-3.24
        apt install meson valac
    - name: Build
      env: 
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  lint:

    runs-on: ubuntu-latest

    container: 
      image: valalang/lint

    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint -d .
